### ISSUE TITLE
docker-entrypoint error

### ISSUE THREAD

**Issue by carlbastos** [kool-dev/docker-wordpress#2]
Hello there 😉 

When running this image on a k8s cluster, I've noticed the following error:

```
/usr/local/bin/docker-entrypoint.sh: line 26: $1: unbound variable
2020/08/12 01:31:08 Command exited with error: exit status 1
```

Rendering the k8s pod unusable, of course.

This might be due to the fact that the image **is not inheriting the default CMD from the original image**, but I am not 100% sure. Further analysis is required on this matter, since `docker-entrypoint.sh` is expecting a parameter (`apache` or `php-fpm`) and this parameter is coming empty, which means it is coming as an unbound variable as displayed by the error above.

On a side note, having the CI/CD check for the default `docker run` command would be a great idea too, since it would have catched this error before we merged the latest PR. Something along the lines of:
```
docker run --rm kooldev/wordpress:7.4-fpm-alpine
```

Cheers!

**Comment by dbpolito** [comment]
Good catch, thanks for the fix.
