### ISSUE TITLE
Enable opcache validate timestamps?

### ISSUE THREAD

**Issue by dbpolito** [kool-dev/docker-wordpress#8]
We often have problems with plugin / wp upgrade as it sometimes caches deleted files... W3TotalCache and Flush Opcache helps but sometimes it requires a full restart.

For WP i think it's recommended just have this enabled.

**Comment by fabriciojs** [comment]
Fine by me

**Comment by dbpolito** [comment]
Nah, after digging it doesn't seem to be a lot of help.
